# This is a TOML document.


#当前使用的环境
[env]
name="go-apns-moa"
runMode="dev"
bindAddress="^10\\.83\\.\\d+\\.\\d+$:13001"
#可以是momokeeper或者zookeeper
registryType="momokeeper"
#service Uri的后缀可以为空
serviceUriSuffix="-dev"

#registry的管理	
[registry]
	[registry.dev]
		hosts="moa_admin.momo.com:10020,moa_lookup.momo.com:10010"
	[registry.online]
		hosts="moa_admin.momo.com:10020,moa_lookup.momo.com:10010" 

#cluster的服务器
[clusters]
	[clusters.dev]
		#env=dev/online
		env="dev" 
		logFile="conf/log_dev.xml"
		processTimeout=5
		#最大分发处理协程数
		maxDispatcherSize=8000 
		#读取缓冲大小 
		readBufferSize=16384 
		#写入缓冲大小
		writeBufferSize=16384 
		#写异步channel长度
		writeChannelSize=1000 
		#读异步channel长度
		readChannelSize=1000 
		
	[clusters.online]
		#env=dev/online
		env="online" 
		logFile="conf/log.xml"
		processTimeout=5
		#最大分发处理协程数
		maxDispatcherSize=8000 
		#读取缓冲大小 
		readBufferSize=16384
		#写入缓冲大小
		writeBufferSize=16384
		#写异步channel长度
		writeChannelSize=1000 
		#读异步channel长度
		readChannelSize=1000 
